### ISSUE TITLE
Need to enable MathJax after installation.

### ISSUE THREAD

**Issue by Topher-the-Geek** [kasperpeulen/discourse-mathjax#15]
I'm running Discourse 1.1.3 in a docker container, and I followed the docker instructions in the README. Math rendering did not work. Eventually I found that I needed to go to my discourse admin "Admin -> Settings -> MathJax plugin" and check "enable mathjax plugin."  Everything was fine then.

I think that either: the installation instructions should to mention this step, or the install should take care of it.

**Comment by kasperpeulen** [comment]
@lidel This change is made by discoursehosting, I think in this way they add the latest version of the mathjax plugin to all their discourse installations, and then let the user decide if they want to use mathjax or not.

I will ask discoursehosting to be sure, and add it to the installation instruction for now.

**Comment by kasperpeulen** [comment]
I close this for now, I think it works fine this way.
