### ISSUE TITLE
Page must be reloaded after editing a post

### ISSUE THREAD

**Issue by wil93** [kasperpeulen/discourse-mathjax#18]
When I create a post with embedded LaTeX and send it, it's correctly rendered (during the preview and after saving). But, if I edit the same post and save it again, then the LaTeX code isn't rendered anymore (and I have to refresh the page).

**Comment by lidel** [comment]
This may be related or even the same issue (happens when Replying):
https://meta.discourse.org/t/mathjax-plugin-supports-math-notation-using-latex/12826/32?u=lidel

**Comment by kasperpeulen** [comment]
fixed with: https://github.com/kasperpeulen/discourse-mathjax/pull/19
